In [1]:
# Definition of NumPy

# NumPy (Numerical Python) is a powerful open-source library in Python used for numerical and scientific computing.
# It provides support for large, multi-dimensional arrays and matrices, along with a collection of mathematical functions to operate on these arrays efficiently.
# NumPy is widely used in data analysis, machine learning, and scientific research due to its speed and versatility.

import numpy as np

# Example: Creating a NumPy array
arr = np.array([1, 2, 3, 4, 5])
print(arr)  # Output: [1 2 3 4 5]

[1 2 3 4 5]


In [2]:
#2D array

arr2 = np.array([[1,2,3],[4,5,6]])

print(arr2)

[[1 2 3]
 [4 5 6]]


In [3]:
#check number of Dimention 

print(arr2.ndim)

2


In [6]:
#Array indexing 

print(arr[0])

print(arr2[1,1])

1
5


In [7]:
# Array slicing example in NumPy

import numpy as np

arr = np.array([10, 20, 30, 40, 50, 60])

# Slicing elements from index 1 to 4 (excluding 4)
print(arr[1:4])  # Output: [20 30 40]

# Slicing from the beginning to index 3 (excluding 3)
print(arr[:3])   # Output: [10 20 30]

# Slicing from index 2 to the end
print(arr[2:])   # Output: [30 40 50 60]

# Slicing with a step of 2
print(arr[::2])  # Output: [10 30 50]

[20 30 40]
[10 20 30]
[30 40 50 60]
[10 30 50]


In [1]:
# Vectorized operations in NumPy

# Vectorized operations allow you to perform element-wise operations on entire arrays without using explicit loops.
# This makes computations faster and code more concise compared to standard Python lists.

import numpy as np

arr1 = np.array([1, 2, 3, 4])
arr2 = np.array([10, 20, 30, 40])

# Element-wise addition
result_add = arr1 + arr2
print("Addition:", result_add)  # Output: [11 22 33 44]

# Element-wise multiplication
result_mul = arr1 * arr2
print("Multiplication:", result_mul)  # Output: [10 40 90 160]

# Element-wise square
result_square = arr1 ** 2
print("Square:", result_square)  # Output: [ 1  4  9 16]

# Applying a function to all elements (e.g., np.sqrt)
result_sqrt = np.sqrt(arr2)
print("Square root:", result_sqrt)  # Output: [3.16227766 4.47213595 5.47722558 6.32455532]

Addition: [11 22 33 44]
Multiplication: [ 10  40  90 160]
Square: [ 1  4  9 16]
Square root: [3.16227766 4.47213595 5.47722558 6.32455532]
